runs:
  using: composite
  steps:
    - uses: actions/setup-node@v6
      with:
        node-version: 22.17.1
    - uses: pnpm/action-setup@v4
      with:
        version: 10.18.3
        run_install: false
    - run: echo "STORE_PATH=$(pnpm store path --silent)" >> $GITHUB_ENV
      shell: bash
    - uses: actions/cache@v4
      with:
        path: ${{ env.STORE_PATH }}
        key: ${{ runner.os }}-pnpm-store-${{ hashFiles('**/pnpm-lock.yaml') }}
        restore-keys: ${{ runner.os }}-pnpm-store-
    - run: pnpm install
      shell: bash
