name: Continuous Integration
on:
  pull_request:
    branches:
      - main
concurrency: ${{ github.workflow }}-${{ github.ref }}
jobs:
  lint:
    name: Lint the source code
    runs-on: ubuntu-latest
    steps:
      - name: Checkout ${{ github.ref }}
        uses: actions/checkout@v5
      - uses: ./.github/actions/install-tools-dependencies
      - name: Lint the packages
        shell: bash
        run: |
          pnpm packages:lint:code
          pnpm packages:lint:markdown
  test:
    name: Test the source code
    runs-on: ubuntu-latest
    needs: lint
    steps:
      - name: Checkout ${{ github.ref }}
        uses: actions/checkout@v5
      - uses: ./.github/actions/install-tools-dependencies
      - name: Test the packages
        shell: bash
        run: pnpm packages:test
  build:
    name: Build the packages
    runs-on: ubuntu-latest
    needs: test
    steps:
      - name: Checkout ${{ github.ref }}
        uses: actions/checkout@v5
      - uses: ./.github/actions/install-tools-dependencies
      - name: Build the packages
        shell: bash
        run: pnpm packages:build
