name: Continuous Release
on:
  push:
    branches:
      - main
concurrency: ${{ github.workflow }}-${{ github.ref }}
jobs:
  lint-and-test:
    name: Lint and test the source code
    runs-on: ubuntu-latest
    steps:
      - name: Checkout ${{ github.ref }}
        uses: actions/checkout@v4
      - uses: ./.github/actions/install-tools-dependencies
      - name: Lint the packages
        shell: bash
        run: |
          bun run packages:lint:code
          bun run packages:lint:markdown
      - name: Unit test the packages
        id: unit-test-packages
        shell: bash
        run: bun run packages:test
  prepare-and-release:
    name: Prepare and release the packages
    runs-on: ubuntu-latest
    needs: lint-and-test
    timeout-minutes: 20
    steps:
      - name: Checkout ${{ github.ref }}
        uses: actions/checkout@v4
      - uses: ./.github/actions/install-tools-dependencies
      - name: Proceed to release
        uses: changesets/action@v1
        with:
          version: bun run ci:version
          publish: bun run ci:release
          commit: "chore: new release candidate"
          title: "New release candidate"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
